### ISSUE TITLE
Question about traing data input format.

### ISSUE THREAD

**Issue by danbo6** [x7jeon8gi/FactorVAE#1]
Hi, Thanks for your implementation which is very impressive!

I have a question about the input data format. IIUC, if the input data dimension is (300,20,8) and 300 means batch size(300 stocks in the batch), 20 means we want the features for that stock from past 20 transaction days,  and 8 means there are 8 features for that stock.  

But in your dataset.py file, you sort the stock data for each day by its label(which is the return of that stock) https://github.com/x7jeon8gi/FactorVAE/blob/main/dataset.py#L47, and you fetch the data from past 20 days by its index https://github.com/x7jeon8gi/FactorVAE/blob/main/dataset.py#L69. I feel there is an issue here, because you can not make sure that you can always fetch data for the same stock from the past 20days in this way https://github.com/x7jeon8gi/FactorVAE/blob/main/dataset.py#L69, say sh30000 may be the first on 2017/12/01, but sh30000 may become the second on 2017/12/02 (because its return is not the biggest on 2017/12/02), then you may get the data from different stock. Then (300,20,8) seems meaningless, since in the data may from different stocks in the past 20 days.

Really looking forward to hearing from your side!

**Comment by x7jeon8gi** [comment]
Dear danbo6,

I sincerely appreciate your comment. I have come to recognize the considerable significance of the point you raised. I apologize for the delay, but please be informed that I have now made the necessary corrections to the dataset. Your guidance in this matter has been immensely helpful, and I am truly grateful for it.

**Comment by danbo6** [comment]
Thank you x7jeon8gi! I'm curious if the performance of this model has been improved or not after this change? Say what is the sharpe ratio now?

**Comment by danbo6** [comment]
You can add me on Telegram, my account is @danzb0, we can have more chats over there, if you feel OK. Thanks!
