### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by Thomas-Frew** [x7jeon8gi/FactorVAE#2]
Hello everyone! I am having an issue when backtesting my model:

The benchmark ['SH000300'] does not exist. Please provide the right benchmark.

Does anyone know why I might be getting this error? Thank you!

**Comment by x7jeon8gi** [comment]
Hello, I hope you received the correct data from your Qlib library.  
See below.
https://github.com/microsoft/qlib/tree/main/scripts/data_collector/yahoo
