### ISSUE TITLE
what is the purpose of group.sort_values(by='LABEL0', ascending=False) in line 50 of dateset.py?

### ISSUE THREAD

**Issue by BigAndSweet** [x7jeon8gi/FactorVAE#4]
group.sort_values(by='LABEL0', ascending=False)  does not change anything of group. Even if we use group.sort_values(by='LABEL0', ascending=False, inplace=True) to change group, then what is its purpose? It seems I cannot find the necessarity from the paper.

**Comment by x7jeon8gi** [comment]
Hello, BigAndSweet. If you get the dataset from Qlib, there are indeed days where there are fewer than 300 stocks in the CSI300 per day. I'm using sort_value to put the empty rows at the tail of the group below.

**Comment by BigAndSweet** [comment]
Thanks. BTW line 142 of module.py should be self.key.shape[1] instead of self.key.shape[0]?

**Comment by x7jeon8gi** [comment]
Wow, you’re right! Thank you very much for pointing out my mistake.
