### ISSUE TITLE
I'd like to ask where and how is your python library installed? Especially qlib, which version is it? Also what's your python version?

### ISSUE THREAD

**Issue by 111change** [x7jeon8gi/FactorVAE#6]
I'd like to ask where and how is your python library installed? Especially qlib, which version is it? Also what's your python version?

**Comment by x7jeon8gi** [comment]
I am using Python 3.8.19 and the PyQLib library version 0.9.3.99.

**Comment by 111change** [comment]
Thank you very much.



---Original---
From: ***@***.***&gt;
Date: Tue, Dec 10, 2024 11:23 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [x7jeon8gi/FactorVAE] I'd like to ask where and how is yourpython library installed? Especially qlib, which version is it? Also what'syour python version? (Issue #6)




 
I am using Python 3.8.19 and the PyQLib library version 0.9.3.99.
